#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

cd src
if [[ `git status . --porcelain` ]]; then
  echo $'\n'$'\e[1;31m'Detected changes in JS src files. Running JS compilation$'\e[0m'$'\n'
  yarn rollup --config rollup.config.js
fi

cd ../dist
if [[ `git status . | grep "not staged"` ]]; then
  echo $'\n'$'\e[1;31m'Detected unstaged changes in JS dist files. Please add changed files$'\e[0m'$'\n'
  exit 1
else
  echo $'\n'$'\e[1;32m'Compiled Javascript files up to date$'\e[0m'$'\n'
fi
